- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Disable nginx Default Virtual Host
  command:
    cmd: unlink /etc/nginx/sites-enabled/default

#- name: Start nginx
#  service:
#    name: nginx
#    state: started
#    enabled: true
