- name: Install MariaDB
  apt:
    name: mariadb-server
    state: present

- name: Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: true

- name: Set MariaDB root password
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    priv: "*.*:ALL"
    state: present

- name: Create a new database for WordPress
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present

- name: Create a new MySQL user for WordPress
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present
